change sriov installation and systemd
suse-edge/misc pull request #100
Opened 2024-06-06 15:11 UTC by alknopfler

- SRIOV installation using HelmChart CR instead of helm install in systemd
- MTU example added to the static IPs

2024-06-06 15:12 UTC, alknopfler commented
-Tested in Lab
```
kube-system       helm-install-sriov-crd-n77vk                              0/1     Completed          0              58m
kube-system       helm-install-sriov-network-operator-qxqmd                 0/1     Completed          0              58m
...
kube-system       sriov-device-plugin-f7d8b                                 1/1     Running            0              31m
kube-system       sriov-network-config-daemon-7thg6                         1/1     Running            1 (32m ago)    44m
kube-system       sriov-network-operator-56698b464-hdb9s                    1/1     Running            1 (32m ago)    44m
kube-system       sriov-network-operator-sriov-nfd-gc-8c789699f-gdjrq       1/1     Running            1 (32m ago)    44m
kube-system       sriov-network-operator-sriov-nfd-master-c97ff9f8d-8l7rt   1/1     Running            1 (32m ago)    44m
kube-system       sriov-network-operator-sriov-nfd-worker-hbkwq             1/1     Running            1 (32m ago)    44m
```

2024-06-06 15:18 UTC, hardys commented
Looks good to me but shall we mark this as a draft until the registry.suse.com charts are available?

2024-06-14 15:37 UTC, Kristian-ZH commented on telco-examples/edge-clusters/dhcp/edge-telco-single-node/telco-capi-single-node-sriov-auto.yaml
> +                    chart: oci://registry.suse.com/edge/charts/sriov-crd-chart
```suggestion
                    chart: oci://registry.suse.com/edge/sriov-crd-chart
```

2024-06-14 15:37 UTC, Kristian-ZH commented on telco-examples/edge-clusters/dhcp/edge-telco-single-node/telco-capi-single-node-sriov-auto.yaml
> +                    chart: oci://registry.suse.com/edge/charts/sriov-network-operator-chart
```suggestion
                    chart: oci://registry.suse.com/edge/sriov-network-operator-chart
```

2024-06-14 16:01 UTC, Kristian-ZH approved these changes

2024-06-16 17:36 UTC, hardys requested changes

2024-06-16 17:36 UTC, hardys commented on telco-examples/edge-clusters/dhcp-less/edge-telco-single-node/telco-capi-single-node-sriov-auto.yaml
> +                    targetNamespace: kube-system
Does this need to use `kube-system`?  The [chart docs](https://github.com/suse-edge/charts/tree/main/charts/sriov-network-operator/1.2.4%2Bup0.1.0#deploy-sr-iov-network-operator) describe using a `sriov-network-operator` namespace which would probably be preferable?

2024-06-16 17:37 UTC, hardys commented
One question re the target namespace, otherwise lgtm

2024-06-17 12:55 UTC, hardys approved these changes

2024-06-17 12:55 UTC, merged