add docs and example to add cacerts
suse-edge/misc pull request #101
Opened 2024-06-11 13:34 UTC by alknopfler

- Add docs to include the custom cacerts
- add an example of secret to be added to the kubernetes manifest folder

2024-06-14 15:29 UTC, Kristian-ZH requested changes

2024-06-14 15:29 UTC, Kristian-ZH commented on telco-examples/mgmt-cluster/multi-node/README.md
> +metadata:
The file is not formatted correctly

2024-06-14 15:29 UTC, Kristian-ZH commented on telco-examples/mgmt-cluster/multi-node/README.md
> +kind: Secret
The file is not formatted correctly

2024-06-14 15:49 UTC, Kristian-ZH commented on telco-examples/mgmt-cluster/single-node/README.md
> +This is an optional step to add certificates to the management cluster to provide images using HTTPS (Helm Chart metal3 Version >= 0.7.1)
```suggestion
This is an optional step to add certificates to the management cluster to provide images using HTTPS Server(Helm Chart metal3 Version >= 0.7.1)
```

2024-06-14 15:51 UTC, alknopfler commented on telco-examples/mgmt-cluster/multi-node/README.md
> +This is an optional step to add certificates to the management cluster to provide images using HTTPS (Helm Chart metal3 Version >= 0.7.1)
changed! thanks

2024-06-14 15:52 UTC, alknopfler commented
changes done!

2024-06-14 15:53 UTC, Kristian-ZH approved these changes

2024-06-14 15:53 UTC, Kristian-ZH commented
/lgtm

2024-06-16 17:32 UTC, hardys approved these changes

2024-06-16 17:32 UTC, merged