add support for rke2 on x86_64 architecture
suse-edge/misc pull request #7
Opened 2023-05-12 10:54 UTC by alknopfler

2023-05-12 11:03 UTC, e-minguez requested changes

2023-05-12 11:03 UTC, e-minguez commented on slemicro/combustion/script
> +	After=network.target network-online.target rancher_installer.service skip-rancher-bootstrap.service elemental_installer.service
Same as before, make it dependant of k3s or rke2 depending on which one has been installed.

2023-05-12 11:03 UTC, e-minguez commented on slemicro/create_vm.sh
> +else # RKE2
I'd say to do a switch instead and fail if this is not rke2 or k3s or false

2023-05-12 11:03 UTC, e-minguez commented on slemicro/env.example
> +export RKE2=true
RKE2 and K3S cannot be enabled at the same time

2023-05-12 11:09 UTC, alknopfler commented on slemicro/combustion/script
> +	After=network.target network-online.target
I think with the ${KUBECTL} wait is far enough, assuming than the timeout is not set

2023-05-13 07:26 UTC, alknopfler commented
Tests realized:
- Cluster envvar false -> Only micro installation: OK
- Cluster envvar not valid: OK
![image](https://github.com/suse-edge/misc/assets/9356454/920f5613-3f96-4c20-b003-f3a838d06c3e)

- Micro + k3s without kube-vip (single node) + rancher + elemental: OK
![image](https://github.com/suse-edge/misc/assets/9356454/0827bb12-85c4-4860-9367-353a989e81ee)

2023-05-16 11:00 UTC, e-minguez commented on slemicro/create_vm.sh
> +
Extra line not needed :P

2023-05-16 11:02 UTC, e-minguez commented on slemicro/combustion/script
> +if [ ${CLUSTER} == "k3s" ]; then
This needs to be tabbed I guess?
IDK if there is another way to do this, but it feels a little bit _dirty_ 😓 let me think about this.

2023-05-17 08:45 UTC, e-minguez requested changes

2023-05-17 08:45 UTC, e-minguez commented on slemicro/README.md
> +# For a single node. This INSTALL_CLUSTER_EXEC will be translated to INSTALL_K3S_EXEC or INSTALL_CLUSTER_EXEC depending on the value of CLUSTER
```suggestion
# For a single node. This INSTALL_CLUSTER_EXEC will be translated to INSTALL_K3S_EXEC or INSTALL_RKE2_EXEC depending on the value of CLUSTER
```

2023-05-17 08:45 UTC, e-minguez commented on slemicro/README.md
> +# To add control plane nodes. This INSTALL_CLUSTER_EXEC will be translated to INSTALL_K3S_EXEC or INSTALL_CLUSTER_EXEC depending on the value of CLUSTER:
```suggestion
# To add control plane nodes. This INSTALL_CLUSTER_EXEC will be translated to INSTALL_K3S_EXEC or INSTALL_RKE2_EXEC depending on the value of CLUSTER:
```

2023-05-17 08:45 UTC, e-minguez commented on slemicro/combustion/script
> +	export KUBECONFIG=${KUBECONFIG}
Again, this is not needed :D

2023-05-17 09:18 UTC, merged